version: "3.9"

services:
  monitor:
    container_name: monitor
    build:
      context: ./monitor
      dockerfile: Dockerfile
    ports:
      - "8001:8001" # change this to your frontend port, if you change this, you need to change the backend service as well
    environment:
      - BACKEND_URL=http://manager:8080/ # change this to your backend url, if you change this, you need to change the backend service as well
      - DEBUG=false # change this to true if you want to see the debug logs
  manager:
    # image: "docker-spring-boot-postgres:latest"
    container_name: manager
    build:
      context: ./manager
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres # change this to your postgres database name, if you change this, you need to change the db service as well
      - SPRING_DATASOURCE_USERNAME=postgres # change this to your postgres username
      - SPRING_DATASOURCE_PASSWORD=postgres # change this to your postgres password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update # change this to update if you want to update the database
    ports:
      - "8080:8080" # change this to your backend port, if you change this, you need to change the frontend service as well
    depends_on:
      - db
    links:
      - db
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - account-id=1 # change this to your account id
      - deposit-uri=http://manager:8080/api/v1/accounts/{account-id}/deposits # change this to your backend url, if you change this, you need to change the backend service as well
      - withdraw-uri=http://manager:8080/api/v1/accounts/{account-id}/withdrawals # change this to your backend url, if you change this, you need to change the backend service as well
    ports:
      - "8082:8082" # change this to your frontend port, if you change this, you need to change the backend service as well
    depends_on:
      - manager
    links:
      - manager
  db:
    image: "postgres:16.0-alpine3.18"
    container_name: db
    environment:
      - POSTGRES_USER=postgres # change this to your postgres username
      - POSTGRES_PASSWORD=postgres # change this to your postgres password
      - POSTGRES_DB=postgres # change this to your postgres database name
    expose:
      - 5432 # change this to your postgres port, make sure it is the same as the one in the db service
    ports:
      - "5432:5432" # change this to your postgres port
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
