apiVersion: v1
kind: Pod
metadata:
  name: client-and-manager-pod
  labels:
    app: manager
spec:
  containers:
    - name: manager
      image: europe-west1-docker.pkg.dev/civil-song-423915-i3/my-repo/manager:latest
      resources:
        requests:
          cpu: 1000m
          memory: "1500Mi"
        limits:
          cpu: 1000m
          memory: "1500Mi"
      ports:
        - containerPort: 8080
      env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/postgres
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
      
      volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
    - name: client-1
      image: europe-west1-docker.pkg.dev/civil-song-423915-i3/my-repo/client:latest
      # ports:
      #   - containerPort: 8082
      env:
        - name: SERVER_PORT
          value: "8082"
        - name: account-id
          value: "1"
        - name: deposit-uri
          value: http://manager-service:8080/api/v1/accounts/{account-id}/deposits
        - name: withdraw-uri
          value: http://manager-service:8080/api/v1/accounts/{account-id}/withdrawals

    - name: client-2
      image: europe-west1-docker.pkg.dev/civil-song-423915-i3/my-repo/client:latest
      # ports:
      #   - containerPort: 8083
      env:
        - name: SERVER_PORT
          value: "8083"
        - name: account-id
          value: "1"
        - name: deposit-uri
          value: http://manager-service:8080/api/v1/accounts/{account-id}/deposits
        - name: withdraw-uri
          value: http://manager-service:8080/api/v1/accounts/{account-id}/withdrawals
  volumes:
    - name: config
      configMap:
        name: postgres-config