apiVersion: v1
kind: Service
metadata:
  name: monitor-service
spec:
  type: LoadBalancer  # Changed from NodePort to LoadBalancer
  selector:
    app: monitor
  ports:
    - protocol: TCP
      port: 80  # Expose the service on port 80, the default HTTP port
      targetPort: 8001  # Port on which your application is running
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          image: europe-west1-docker.pkg.dev/civil-song-423915-i3/my-repo/monitor:latest
          ports:
            - containerPort: 8001
          env:
            # - name: REACT_APP_BACKEND_URL
            #   value: http://manager-service:8080
            - name: DEBUG
              value: "false"