apiVersion: v1
kind: Service
metadata:
  name: monitor-service
spec:
  selector:
    app: monitor
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          image: https://europe-west1-docker.pkg.dev/civil-song-423915-i3/my-repo/monitor:latest
          ports:
            - containerPort: 8001
          env:
            - name: BACKEND_URL
              value: http://manager-service:8080/
            - name: DEBUG
              value: "false"
