server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: managerApplication
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

account:
  id: e3bb63ce-9e48-423f-9da9-e40f51f9fb77
