server:
  port: 8082
spring:
  application:
    name: client

account-id: 1
deposit-uri: http://localhost:8080/api/v1/accounts/{accountId}/deposits
withdraw-uri: http://localhost:8080/api/v1/accounts/{accountId}/withdrawals
