export const mockSearchResults = {
  count: 4,
  result: [
    {
      description: "APPLE INC",
      displaySymbol: "AAPL",
      symbol: "AAPL",
      type: "Common Stock",
    },
    {
      description: "APPLE INC",
      displaySymbol: "AAPL.SW",
      symbol: "AAPL.SW",
      type: "Common Stock",
    },
    {
      description: "APPLE INC",
      displaySymbol: "APC.BE",
      symbol: "APC.BE",
      type: "Common Stock",
    },
    {
      description: "APPLE INC",
      displaySymbol: "APC.DE",
      symbol: "APC.DE",
      type: "Common Stock",
    },
  ],
};

export const mockCompanyDetails = {
  address: "1 Apple Park Way",
  city: "CUPERTINO",
  country: "US",
  currency: "USD",
  cusip: "",
  sedol: "2046251",
  description:
    "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four technology companies, alongside Amazon, Google, and Microsoft. The company's hardware products include the iPhone smartphone, the iPad tablet computer, the Mac personal computer, the iPod portable media player, the Apple Watch smartwatch, the Apple TV digital media player, the AirPods wireless earbuds and the HomePod smart speaker. Apple's software includes the macOS, iOS, iPadOS, watchOS, and tvOS operating systems, the iTunes media player, the Safari web browser, the Shazam acoustic fingerprint utility, and the iLife and iWork creativity and productivity suites, as well as professional applications like Final Cut Pro, Logic Pro, and Xcode. Its online services include the iTunes Store, the iOS App Store, Mac App Store, Apple Music, Apple TV+, iMessage, and iCloud. Other services include Apple Store, Genius Bar, AppleCare, Apple Pay, Apple Pay Cash, and Apple Card.",
  employeeTotal: "137000",
  exchange: "NASDAQ/NMS (GLOBAL MARKET)",
  ggroup: "Technology Hardware & Equipment",
  gind: "Technology Hardware, Storage & Peripherals",
  gsector: "Information Technology",
  gsubind: "Technology Hardware, Storage & Peripherals",
  ipo: "1980-12-12",
  isin: "",
  marketCapitalization: 1415993,
  naics: "Communications Equipment Manufacturing",
  naicsNationalIndustry:
    "Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing",
  naicsSector: "Manufacturing",
  naicsSubsector: "Computer and Electronic Product Manufacturing",
  name: "Apple Inc",
  phone: "14089961010",
  shareOutstanding: 4375.47998046875,
  state: "CALIFORNIA",
  ticker: "AAPL",
  weburl: "https://www.apple.com/",
  logo: "https://static.finnhub.io/logo/87cb30d8-80df-11ea-8951-00000000092a.png",
  finnhubIndustry: "Technology",
};

export const mockstockQuote = {
  c: 261.74,
  h: 263.31,
  l: 260.68,
  o: 261.07,
  pc: 259.45,
  t: 1582641000,
};

export const mockHistoricalData = {
  c: [217.68, 221.03, 219.89],
  h: [222.49, 221.5, 220.94],
  l: [217.19, 217.1402, 218.83],
  o: [221.03, 218.55, 220],
  s: "ok",
  t: [1569297600, 1569384000, 1569470400],
  v: [33463820, 24018876, 20730608],
};

export const mockTransactionData = {
  count: 10,
  offset: 0,
  total: 100,
  entries: [
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
    {
      id: 1,
      href: "api/transactions/1",
      user: {
        id: 1,
        href: "api/users/1",
        username: "user1",
        name: "John Doe",
      },
      type: "withdrawal",
      amount: 100,
      date: "2022-01-01",
      status: "completed",
    },
  ],
};
